booted_cmds:
  names:
  - voxel_grid_filter
  - ndt_matching
  - vehicle_model
calibration_publisher:
  camera_frame: camera
  camera_id: ''
  camera_info_topic: /camera_info
  file: ''
  image_topic_src: /image_raw
  projection_matrix_topic: /projection_matrix
  publish_camera_info: true
  publish_extrinsic_mat: true
  register_lidar2camera_tf: true
  target_frame: velodyne
car_dpm:
  Lambda: 10
  group_threshold: 0.1
  num_bins: 9
  num_cells: 8
  score_threshold: -0.5
car_fusion:
  car: true
  dispersion: 1.0
  max_height: 2.0
  max_low_height: -1.0
  min_low_height: -1.5
  min_points: 2
  pedestrian: false
  sync: false
car_kf:
  camera_id: ''
  carHEAD: true
  default_lifespan: 8
  error_estimate_covariance: 1000000.0
  initial_lifespan: 4
  measurement_noise_covariance: 25.0
  noise_covariance: 1.0
  orb_features: 2000
  pedestrian: false
  percentage_of_overlapping: 0.0
  sync: false
  use_orb: 0
detection_qs:
  file: ''
lanelet_map:
  file_name: ''
localization_qs:
  file: ''
map_qs:
  file: ''
mission_planning_qs:
  file: ''
motion_planning_qs:
  file: ''
ndt_matching:
  error_threshold: 1.0
  get_height: false
  imu_topic: !!python/unicode '/imu_raw'
  imu_upside_down: false
  init_pos_gnss: 1
  max_iterations: 30
  method_type: 0
  output_log_data: false
  pitch: 0.0
  resolution: 1.0
  roll: 0.0
  step_size: 0.1
  sync: false
  trans_epsilon: 0.01
  use_imu: false
  use_odom: false
  use_predict_pose: 1
  x: 0.0
  y: 0.0
  yaw: 0.0
  z: 0.0
pcd_binarizer:
  path_pcd_binarizer: ''
  point_type: !!python/unicode 'PointXYZ'
pcd_filter:
  leaf_size: 0.2
  path_pcd_filter: ''
  point_type: !!python/unicode 'PointXYZ'
pedestrian_dpm:
  Lambda: 10
  group_threshold: 0.3
  num_bins: 9
  num_cells: 8
  score_threshold: 0.6
pedestrian_fusion:
  dispersion: 1.0
  max_height: 2.0
  max_low_height: -1.0
  min_low_height: -1.5
  min_points: 2
pedestrian_kf:
  default_lifespan: 8
  error_estimate_covariance: 1000000.0
  initial_lifespan: 4
  measurement_noise_covariance: 25.0
  noise_covariance: 1.0
  orb_features: 2000
  percentage_of_overlapping: 0.0
  use_orb: 0
play_rosbag_play:
  file: ''
  rate: ''
  repeat: false
  start: 0
point_cloud:
  path_area_list: None
  path_pcd: ''
  scene_num: noupdate
points_concat_filter:
  input_topics: '[/points_alpha,/points_beta]'
  output_frame_id: velodyne
  output_topic: /points_concat
points_image:
  camera_id: ''
  sync: false
ray_ground_filter:
  base_frame: base_link
  clipping_height: 2.0
  concentric_divider_distance: 0.0
  general_max_slope: 5
  input_point_topic: !!python/unicode '/points_raw'
  local_max_slope: 8
  min_height_threshold: 0.05
  min_point_distance: 1.85
  radial_divider_angle: 0.08
  reclass_distance_threshold: 0.2
sensing_qs:
  file: ''
setup_tf:
  frame_id: /base_link
  localizer_cmd_param: /velodyne
  localizer_rosparam: velodyne
  period_in_ms: 10
  pitch: 0.0
  roll: 0.0
  x: 0.0
  y: 0.0
  yaw: 0.0
  z: 2.4
tf:
  file: ''
vector_map:
  path_vec: ''
vehicle_info:
  info_path: ''
vehicle_model:
  model_path: ''
vel_pose_connect:
  sim_mode: false
  topic_pose_stamped: /ndt_pose
  topic_twist_stamped: /estimate_twist
virtual_scan_image:
  camera_id: ''
  sync: false
voxel_grid_filter:
  measurement_range: 200
  points_topic: /points_raw
  sync: false
  voxel_leaf_size: 2.0
waypoint_clicker:
  output_file: /tmp/lane_waypoint.csv
  velocity: 40.0
waypoint_saver:
  input_type: 0
  interval: 1.0
  lane_topic: !!python/unicode '/lane_waypoints_array'
  save_filename: /home/autoware/shared_dir/Town03.csv
  save_velocity: true
